### ISSUE TITLE
Codeium 1.10.7 error

### ISSUE THREAD

**Issue by hcymysql** [Exafunction/codeium#76]
Unhandled exception in [StandaloneCoroutine{Cancelling}@7f2bb070, Dispatchers.IO]

java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:88)
	at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:68)
	at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:51)
	at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
	at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
	at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
	at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@7f2bb070, Dispatchers.IO]

**Comment by akash240577** [comment]
Same error:
Unhandled exception in Dispatchers.IO

java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:184)
	at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:90)
	at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:70)
	at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:53)
	at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
	at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
	at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
	at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@1c9009a2, Dispatchers.IO]

**Comment by weidlu** [comment]
+1
  Unhandled exception in [StandaloneCoroutine{Cancelling}@74e11e55, Dispatchers.IO]
  
  java.lang.IllegalArgumentException: Invalid URL port: "0"
at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1330)
at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
at okhttp3.Request$Builder.url(Request.kt:184)
at com.codeium.intellij.chat_server_client.ChatServerClient.establishConnection(ChatServerClient.kt:90)
at com.codeium.intellij.chat_server_client.ChatServerClient.<init>(ChatServerClient.kt:70)
at com.codeium.intellij.chat_server_client.ChatServerClientMultiton$Companion.getInstance(ChatServerClient.kt:53)
at com.codeium.intellij.chat_window.ChatViewLoader.getClientUrl(ChatViewLoader.kt:48)
at com.codeium.intellij.chat_window.ChatViewerWindow.loadClient(ChatViewerWindow.kt:126)
at com.codeium.intellij.chat_window.ChatViewerWindow.access$loadClient(ChatViewerWindow.kt:45)
at com.codeium.intellij.chat_window.ChatViewerWindow$1.invokeSuspend(ChatViewerWindow.kt:74)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@74e11e55, Dispatchers.IO]

codeium version: 1.10.11
intellij idea version: 2023.2.5

**Comment by IvanGnusarkov** [comment]
Same on idea ultimate 2022.3.3, codeium 1.10.11

**Comment by IvanGnusarkov** [comment]
updated to 1.12.6, error is gone. thanks
