### ISSUE TITLE
command 'codeium.openProfile' not found

### ISSUE THREAD

**Issue by WillHe2020** [Exafunction/codeium#77]
VSCode displayed an error message when trying to execute the 'codeium.openChatInPane' command.

**Comment by peppapig13132** [comment]
I have same issue.
We can see the error message when I click Codeium profile button.

![image](https://github.com/user-attachments/assets/6bc913e7-c30a-4b43-82d6-c2f5d09e2c20)

**Comment by cauevsilva** [comment]
@WillHe2020 , @peppapig13132 , I am not associated with codeium, but just got the same issue on my end. 

When I opened VSCode, it showed an auto-update happened. I imagine the issue could be related to the update changes. 

The solution was: uninstall the extension, and re-install it. The fresh install logged me in automatically, but it was failing to download the language server. 

Then:
- Toggle Autocomplete Globally
- Disable the extension
- Re-enable the extension
- Enable Autocomplete Globally.

Now the language server was able to connect properly.

You can probably skip the uninstall / reinstall and go straight to the autocomplete steps. 
 
Hope it helps.

edit: included extra steps  that actually brought it back to functional.

**Comment by peppapig13132** [comment]
Tried with both the latest version of VS Code(1.92.2) and Codeium(v1.13.3).
I still can't login the Codeium with the error message `command 'codeium.openProfile' not found`.

Installation output message:
```
2024-08-16 00:45:06.186 [info] Started local extension host with pid 23692.
2024-08-16 00:47:24.629 [error] View already awaiting revival: Error: View already awaiting revival
    at y.resolve (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1434:18695)
    at vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2429:35875
    at async k (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2430:1949)
```

```
2024-08-16 01:34:04.955 [info] Extension host with pid 21348 started
2024-08-16 01:34:04.994 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-08-16 01:34:05.007 [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
2024-08-16 01:34:05.385 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-08-16 01:34:05.557 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-08-16 01:34:06.071 [info] Eager extensions activated
2024-08-16 01:34:06.099 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-08-16 01:34:06.159 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-08-16 01:34:06.501 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-08-16 01:34:49.404 [info] ExtensionService#_doActivateExtension Codeium.codeium, startup: false, activationEvent: 'onStartupFinished'
2024-08-16 01:34:52.071 [error] Activating extension Codeium.codeium failed due to an error:
2024-08-16 01:34:52.072 [error] TypeError: Invalid URL
	at new URL (node:internal/url:797:36)
	at new en (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:491670)
	at Object.on [as transport] (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:495322)
	at new me (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:451241)
	at new Mt (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:485760)
	at new Ut (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:490028)
	at t.sentryInit (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:1728006)
	at c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:970404
	at f (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:961415)
	at Generator.<anonymous> (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:962757)
	at Generator.next (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:961844)
	at s (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:967318)
	at a (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:967521)
	at c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:967580
	at new Promise (<anonymous>)
	at c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:967461
	at te (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:988463)
	at ee (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:969308)
	at c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:969001
	at f (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:961415)
	at Generator.<anonymous> (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:962757)
	at Generator.next (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:961844)
	at s (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:967318)
	at a (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:967521)
	at c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:967580
	at new Promise (<anonymous>)
	at c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:967461
	at $ (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:969261)
	at t.activate (c:\Users\Admin\.vscode\extensions\codeium.codeium-1.10.11\dist\extension.js:2:988558)
	at z.kb (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13608)
	at z.jb (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13280)
	at c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:11267
	at async m.n (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
	at async m (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
	at async m.l (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829)
```

**Comment by guhagourab** [comment]
Facing the same issue. I tried uninstall/install and then restart the extension. But the issue still persists

**Comment by yassine017** [comment]
same issue here ,, for two weeks I could not get it to work , is nobody really not looking into this?

**Comment by yassine017** [comment]
I was able to resolve it by removing the .codeium in my home directory (I'm on debian12)... I guess you could try a similar thing

**Comment by caueatdovly** [comment]
that's a good point. I didn't mention that my issue was on Mac. 

For windows, linux, we will need to hear from the Codeium team. 

But this steps fixed it for me: 

    Toggle Autocomplete Globally
    Disable the extension
    Re-enable the extension
    Enable Autocomplete Globally.

**Comment by guhagourab** [comment]
I am still getting it in my windows unfortunately. Using a different pair
programming tool but I miss codium.

**Comment by myself-pabitra** [comment]
(VSCode) 2024-09-21 16:06:47.332 [INFO]: win-ca initialized
(VSCode) 2024-09-21 16:06:49.547 [INFO]: Creating manager directory: C:\Users\HP\AppData\Local\Temp\b8c0b417-efd5-433c-a078-57eed640cc6a\codeium\manager
(VSCode) 2024-09-21 16:06:49.548 [INFO]: b2ac6b671b2a7410ad5b449085aea9477382618c not found, downloading language server
(VSCode) 2024-09-21 16:06:58.072 [INFO]: Language server started
2024/09/21 16:06:58 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
I0921 16:06:58.234129  6612 main.go:415] [Logging] Initialized the logger
I0921 16:06:58.234129  6612 main.go:503] Setting GOMAXPROCS to 8
I0921 16:06:58.241605  6612 main.go:605] Release 1.10.6 (b2ac6b671b2a7410ad5b449085aea9477382618c)
I0921 16:06:58.241605  6612 main.go:663] Starting language server manager with pid 6612
I0921 16:06:58.243610  6612 main.go:118] Manager acquired its lock file C:\Users\HP\AppData\Local\Temp\b8c0b417-efd5-433c-a078-57eed640cc6a\codeium\manager/locks/manager.lock
F0921 16:06:58.982661  6612 main.go:227] Failed to start language server: fork/exec c:\Users\HP\.vscode\extensions\codeium.codeium-1.10.6\dist\b2ac6b671b2a7410ad5b449085aea9477382618c\language_server_windows_x64.exe: Access is denied.
(VSCode) 2024-09-21 16:06:58.987 [INFO]: Language server exited with code 1




Facing Same issue

**Comment by Sharevex** [comment]
Did you find any fix ?

**Comment by Sharevex** [comment]
Any Fix ?
@peppapig13132

**Comment by guangyi1105** [comment]
@cauevsilva cauevsilva
I followed your method, but the problem remains the same.

**Comment by peppapig13132** [comment]
It's weird 🤔
A few days ago, I've installed the OS(Windows 11) and installed the extension.
It works correctly.

**Comment by KevinHerklotz** [comment]
Had the same problem. I couldn't execute any command on Windows. I uninstalled the extension, closed and reopened VSCode and installed it again. Now it works. (first I tried without restarting VSCode, but that didn't help)

**Comment by 1ndoryu** [comment]
I went several weeks without using it because it wouldn't load until I deleted the .codeium folder in the Windows user folder, and then it started working again. I guess I’ll have to do this every time the program fails.

**Comment by mdancho84** [comment]
Removing the .codeium folder fixed.

**Comment by AscEmon** [comment]
Facing same issues
