### ISSUE TITLE
Client codeium: connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by blueseye** [Exafunction/codeium#94]
![image](https://github.com/user-attachments/assets/0bae5d45-c7de-4377-9c1b-04962401008d)

I0919 23:49:51.075237 34484 server.go:255] LSP listening on random port at 61604
I0919 23:49:51.078035 34484 web_server.go:250] Chat Web Server listening at ws://127.0.0.1:61606
I0919 23:49:51.096731  7928 main.go:295] LS MANAGER: Language server manager found random server port 61599
I0919 23:49:51.096731  7928 main.go:296] LS MANAGER: Language server manager found random lsp port 61604
I0919 23:49:51.096731  7928 main.go:303] LS MANAGER: Language server manager attempting to connect to language server at 127.0.0.1:61599
I0919 23:49:51.121128  7928 main.go:174] LS MANAGER: Fixing language server port at 61599
I0919 23:49:51.121128  7928 main.go:354] LS MANAGER: Language server manager successfully connected to new language server at 127.0.0.1:61599
61604
(VSCode) 2024-09-19 23:49:51.424 [INFO]: Found language server running on port 61599
I0919 23:49:51.444525 34484 utils.go:228] Analyzing workspace files for c:/workplace
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x78 pc=0xd48777]

goroutine 167 [running]:
github.com/Exafunction/Exafunction/exa/fs.PathFromUriString({0xc003289960?, 0xc002c93488?})
	exa/fs/uri.go:118 +0x57
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.SafeFilename({{0xc003289960?, 0xc001fb85a0?}})
	exa/fs/workspace_manager/utils.go:62 +0x34
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.shouldIgnorePath({{}, {0x4630910?, 0xc001fb85a0?}, {0xc002cb6d20?, 0x0?}}, {0xc002cb1500, 0x2, 0x0?})
	exa/fs/workspace_manager/utils.go:180 +0x232
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.IsTrackedPath(...)
	exa/fs/workspace_manager/utils.go:200
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.ComputeWorkspaceFiles.func1({{}, {0x4630910?, 0xc001fb85a0?}, {0xc002cb6d20?, 0x4f6cfc78?}}, {0x4611c08, 0xc00131d880}, {0x0?, 0x0?})
	exa/fs/workspace_manager/utils.go:252 +0x2a5
github.com/Exafunction/Exafunction/exa/fs.Path.WalkDir.func1({0xc002cb6d20?, 0x0?}, {0x4611c08?, 0xc00131d880?}, {0x0?, 0x0?})
	exa/fs/path.go:239 +0x5e
io/fs.walkDir({0x510edd10, 0xc001fb85a0}, {0xc002cb6d20, 0x14}, {0x4611c08, 0xc00131d880}, 0xc002c93a58)
	GOROOT/src/io/fs/walk.go:73 +0x6c
io/fs.walkDir({0x510edd10, 0xc001fb85a0}, {0xc002cb69cb, 0x9}, {0x4611c40, 0xc001fb9370}, 0xc002c93a58)
	GOROOT/src/io/fs/walk.go:95 +0x2bf
io/fs.WalkDir({0x510edd10, 0xc001fb85a0}, {0xc002cb69cb, 0x9}, 0xc002c93a58)
	GOROOT/src/io/fs/walk.go:122 +0xa5
github.com/hack-pad/hackpadfs.WalkDir(...)
	external/com_github_hack_pad_hackpadfs/fs.go:136
github.com/Exafunction/Exafunction/exa/fs.Path.WalkDir({{}, {0x4630910?, 0xc001fb85a0?}, {0xc002cb69cb?, 0x3806348?}}, 0x9880648?)
	exa/fs/path.go:247 +0x92
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.ComputeWorkspaceFiles({{}, {0x4630910?, 0xc001fb85a0?}, {0xc002cb69cb?, 0x14?}}, {0xc002cb1500, 0x2, 0x2}, 0x0)
	exa/fs/workspace_manager/utils.go:232 +0x285
github.com/Exafunction/Exafunction/exa/fs/workspace_manager.(*WorkspaceInfoManager).AddWorkspaceFolder(0xc00199b200, {{0xc002cb69c0?, 0xc00052ada4?}})
	exa/fs/workspace_manager/workspace_manager.go:206 +0x699
github.com/Exafunction/Exafunction/exa/language_server/lsp.(*LspClient).AddWorkspaceFolder(0x34c8c80?, {0xc002cb69a8, 0x16})
	exa/language_server/lsp/lsp.go:91 +0xa4
github.com/Exafunction/Exafunction/exa/language_server/lsp.(*LspClient).Initialize(0xc0025925c0, {0x2f76740?, 0xc0018e6b00?}, 0xffffffffffffffff?)
	exa/language_server/lsp/lsp.go:116 +0x6a
go.lsp.dev/protocol.serverDispatch({0x4611a80, 0xc002682000}, {0x46b9030, 0xc0025925c0}, 0xc0032968e0, {0x509f3e40, 0xc0032a2880})
	external/dev_lsp_go_protocol/server.go:76 +0x1036
github.com/Exafunction/Exafunction/exa/language_server/lsp.Serve.ServerHandler.func2({0x4611a80, 0xc002682000}, 0xc0032968e0, {0x509f3e40, 0xc0032a2880})
	external/dev_lsp_go_protocol/server.go:36 +0x7e
go.lsp.dev/jsonrpc2.(*conn).run(0xc002a33270, {0x4611a80, 0xc002682000}, 0xc002184000)
	external/dev_lsp_go_jsonrpc2/conn.go:206 +0x33f
created by go.lsp.dev/jsonrpc2.(*conn).Go in goroutine 122
	external/dev_lsp_go_jsonrpc2/conn.go:189 +0x8f
(VSCode) 2024-09-19 23:49:51.586 [ERROR]: [unavailable] connect ECONNREFUSED 127.0.0.1:61599
(VSCode) 2024-09-19 23:49:51.865 [ERROR]: [unavailable] connect ECONNREFUSED 127.0.0.1:61599

**Comment by jarvis2324** [comment]
Having similar issue, any solutions yet?

**Comment by blueseye** [comment]
I roll back to the last version (1.14.12), works fine.

**Comment by jarvis2324** [comment]
@blueseye Thanks

**Comment by Ahmed28875** [comment]
![channels4_banner (1)](https://github.com/user-attachments/assets/c7cd05cd-b5c8-49c5-944b-7c8be6c7b45a)
